# Generated by Django 3.2.7 on 2021-09-04 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('current_balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amt', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='basicbanking.customer')),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='basicbanking.customer')),
            ],
        ),
    ]
