# Generated by Django 3.2.7 on 2021-09-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicbanking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='From',
        ),
        migrations.AddField(
            model_name='transaction',
            name='From',
            field=models.ManyToManyField(related_name='sender', to='basicbanking.Customer'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='To',
        ),
        migrations.AddField(
            model_name='transaction',
            name='To',
            field=models.ManyToManyField(related_name='receiver', to='basicbanking.Customer'),
        ),
    ]
