# Generated by Django 3.2.7 on 2021-09-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicbanking', '0003_alter_transaction_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='From',
        ),
        migrations.AddField(
            model_name='transaction',
            name='From',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='To',
        ),
        migrations.AddField(
            model_name='transaction',
            name='To',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
